### ISSUE TITLE
Outdated examples use unity-builder v0.1 => no Android support

### ISSUE THREAD

**Issue by SimonPreisinger** [Unity-CI/Website#35]
**Describe the bug**
Outdated examples use unity-builder v0.1 => no Android support
should be updated
https://unity-ci.com/docs/github/getting-started

**To Reproduce**

-use advanced-example and add Android without changing the unity-builder version

**Expected behavior**
no build error for Android

**Screenshots**

**Additional context**
fast fix is to update to unity-builder v1.2 instead version unity-builderv0.10

**Comment by webbertakken** [comment]
@SimonPreisinger could you please edit your opening post to more clearly describe the issue? 

Anything Android that is not working is probably related to the image: https://gitlab.com/gableroux/unity3d/-/issues/85
