### ISSUE TITLE
Add an edit on github button to each documentation pages dynamically

### ISSUE THREAD

**Issue by GabLeRoux** [Unity-CI/Website#44]
**Is your feature request related to a problem? Please describe.**
Right now, one must click on the github icon, guess that the documentation needs to be updated on the Website repository and then search for the file to edit to be able to provide documentation updates.

![image](https://user-images.githubusercontent.com/1264761/95374886-e7208f80-08ac-11eb-99e5-28f8f94bfc2c.png)

**Describe the solution you'd like**
To make things easier, there should be a button on each page with a edit on github. A good example of this is on [Fastlane's documentation website](https://docs.fastlane.tools/)

**Additional context**
* The solution must be dynamic and not hardcoded on every page.
* The solution should be UX friendly

**Comment by iddify** [comment]
i'm on this, any idea where the button placed on the layout?

**Comment by webbertakken** [comment]
Personally I really like the simplicity of the two links at the bottom like in the [react docs](https://reactjs.org/docs/getting-started.html). This is also where I look for them myself when I want to improve someones docs.

![image](https://user-images.githubusercontent.com/20756439/95389998-f75c5d00-08f4-11eb-910c-06c9365db456.png)

**Comment by webbertakken** [comment]
This was implemented in mentioned PR. Thank you!
